<b>Exercícios

In [14]:
import numpy as np

'''
arr = input().strip().split(' ')
result = arrays(arr)
print(result)
'''


num = '1 2 3 4 -8 -10'
lines = num.split(' ')
v_float = np.array(lines,float)
np.sort(v_float)
print(v_float[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [17]:
num = '1 2 3 4 5 6 7 8 9'
lines = num.split(' ')
v = np.array(lines,int)

v.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
import numpy as np

arr = input().strip().split(' ')
v =  np.array(arr,int)
print(v.reshape(3,3))

10


ValueError: cannot reshape array of size 1 into shape (3,3)

SyntaxError: unexpected EOF while parsing (<ipython-input-24-81307833a175>, line 10)

In [2]:
import numpy as np

arr_size = np.array(input().strip().split(' '),int)
new_arr = np.ones(arr_size[1],arr_size[0])

for i in range(arr_size[0]):
    n = np.array(input().strip().split(' '),int)
    if n.size <= arr_size[1]:
        new_arr = np.vstack([new_arr, n])
    
v = new_arr[1::]

print(v.T)
print(v.flatten())

2 3
10 101 10
10 10 10
[[ 10  10]
 [101  10]
 [ 10  10]]
[ 10 101  10  10  10  10]


In [ ]:
import numpy as np

arr_size = np.array(input().strip().split(' '),int)
new_arr = np.zeros((1,arr_size[2]),int)

print(new_arr)

for i in range( arr_size[1]+arr_size[0]):
    n = np.array(input().strip().split(' '),int)
    if n.size == arr_size[2]:
       #print(new_arr, n)
       new_arr = np.concatenate((new_arr, [n]), axis = 0)
    
v = new_arr[1::]

print(v)

In [ ]:
import numpy as np

np.set_printoptions(legacy='1.13')
    
arr_size = tuple(map(int,input().strip().split(' ')))

print(np.zeros(arr_size,int))
print(np.ones(arr_size,int))